### ISSUE TITLE
Report  Illegal value for `line`

### ISSUE THREAD

**Issue by dandreikiv** [vknabel/vscode-swiftlint#1]
`Error: Illegal value for `line`
	at h._lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:384:469)
	at Object.lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:383:464)
	at /Users/dma-dev/.vscode/extensions/vknabel.vscode-swiftlint-1.0.0/out/lint.js:50:31
	at Array.map (<anonymous>)
	at Object.<anonymous> (/Users/dma-dev/.vscode/extensions/vknabel.vscode-swiftlint-1.0.0/out/lint.js:26:37)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/dma-dev/.vscode/extensions/vknabel.vscode-swiftlint-1.0.0/out/lint.js:5:58)`

**Comment by vknabel** [comment]
Hi @dandreikiv!
Thanks for your report.

Could you post the file and your swiftlint config in here?
Was there a linter warning/error on the the last/first line?

**Comment by derekli66** [comment]
Hi @vknabel 

I also got this error few days ago. This error will happen when you type at the last line of your file.
There are a screenshot and a bug reproduction video below.  Hope this will help.

### Error

`Error: Illegal value for `line`
	at h._lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:384:469)
	at Object.lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:383:464)
	at /Users/derekli/.vscode/extensions/vknabel.vscode-swiftlint-1.0.0/out/lint.js:50:31
	at Array.map (<anonymous>)
	at Object.<anonymous> (/Users/derekli/.vscode/extensions/vknabel.vscode-swiftlint-1.0.0/out/lint.js:26:37)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/derekli/.vscode/extensions/vknabel.vscode-swiftlint-1.0.0/out/lint.js:5:58)`

### Screenshot

<img width="1045" alt="Screen Shot 2019-12-12 at 5 37 31 AM" src="https://user-images.githubusercontent.com/934373/70662810-f0979600-1ca1-11ea-8f06-b308f6195ebf.png">

### Bug Reproduction Demo

https://youtu.be/qdQYTSTAVKI

**Comment by vknabel** [comment]
Thanks @derekli66 for all those great details!
Has been fixed in [1.0.1](https://github.com/vknabel/vscode-swiftlint/releases/tag/1.0.1)
