### ISSUE TITLE
Report  Illegal value for `line`

### ISSUE THREAD

**Issue by derekli66** [vknabel/vscode-swiftlint#2]
`Error: Illegal value for `line`
	at h._lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:384:469)
	at Object.lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:383:464)
	at /Users/derekli/.vscode/extensions/vknabel.vscode-swiftlint-1.0.0/out/lint.js:50:31
	at Array.map (<anonymous>)
	at Object.<anonymous> (/Users/derekli/.vscode/extensions/vknabel.vscode-swiftlint-1.0.0/out/lint.js:26:37)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/derekli/.vscode/extensions/vknabel.vscode-swiftlint-1.0.0/out/lint.js:5:58)`

**Comment by derekli66** [comment]
duplicate issue. Just close it.
