### ISSUE TITLE
Report  Map keys must be unique

### ISSUE THREAD

**Issue by onurATpiksel** [vknabel/vscode-swiftlint#26]
```
YAMLSemanticError: Map keys must be unique; "disabled_rules" is repeated
	at Object.parseMap [as resolve] (/Users/onurdikyar/.vscode/extensions/vknabel.vscode-swiftlint-1.2.7/node_modules/yaml/dist/schema/parseMap.js:80:27)
	at Schema.resolveNode (/Users/onurdikyar/.vscode/extensions/vknabel.vscode-swiftlint-1.2.7/node_modules/yaml/dist/schema/index.js:182:27)
	at Schema.resolveNodeWithFallback (/Users/onurdikyar/.vscode/extensions/vknabel.vscode-swiftlint-1.2.7/node_modules/yaml/dist/schema/index.js:205:22)
	at Document.resolveNode (/Users/onurdikyar/.vscode/extensions/vknabel.vscode-swiftlint-1.2.7/node_modules/yaml/dist/Document.js:503:22)
	at /Users/onurdikyar/.vscode/extensions/vknabel.vscode-swiftlint-1.2.7/node_modules/yaml/dist/Document.js:231:26
	at Array.forEach (<anonymous>)
	at Document.parseContents (/Users/onurdikyar/.vscode/extensions/vknabel.vscode-swiftlint-1.2.7/node_modules/yaml/dist/Document.js:224:14)
	at Document.parse (/Users/onurdikyar/.vscode/extensions/vknabel.vscode-swiftlint-1.2.7/node_modules/yaml/dist/Document.js:157:10)
	at parseDocument (/Users/onurdikyar/.vscode/extensions/vknabel.vscode-swiftlint-1.2.7/node_modules/yaml/dist/index.js:68:37)
	at Object.parse (/Users/onurdikyar/.vscode/extensions/vknabel.vscode-swiftlint-1.2.7/node_modules/yaml/dist/index.js:79:15)
	at Function.<anonymous> (/Users/onurdikyar/.vscode/extensions/vknabel.vscode-swiftlint-1.2.7/out/SwiftLintConfig.js:37:33)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/onurdikyar/.vscode/extensions/vknabel.vscode-swiftlint-1.2.7/out/SwiftLintConfig.js:5:58)
os: darwin
```

**Comment by vknabel** [comment]
Hey @onurATpiksel! Thanks for your feedback. It seems like your Swiftlint config contains `disabled_rules` multiple times.
