### ISSUE TITLE
Report E2BIG spawn E2BIG

### ISSUE THREAD

**Issue by alejandrostateside** [vknabel/vscode-swiftlint#27]
```
Error: spawn E2BIG
	at ChildProcess.spawn (internal/child_process.js:394:11)
	at spawn (child_process.js:549:9)
	at Object.execFile (child_process.js:233:17)
	at Object.module.<computed> [as execFile] (electron/js2c/asar.js:163:31)
	at /Users/jose.artavia/.vscode/extensions/vknabel.vscode-swiftlint-1.2.6/out/lint.js:154:38
	at new Promise (<anonymous>)
	at execSwiftlint (/Users/jose.artavia/.vscode/extensions/vknabel.vscode-swiftlint-1.2.6/out/lint.js:153:12)
	at Object.<anonymous> (/Users/jose.artavia/.vscode/extensions/vknabel.vscode-swiftlint-1.2.6/out/lint.js:59:38)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/jose.artavia/.vscode/extensions/vknabel.vscode-swiftlint-1.2.6/out/lint.js:5:58)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
os: darwin
```

**Comment by alejandrostateside** [comment]
Hello guys, just realized this extension is broken, I tested previous versions but it still didn't work

**Comment by vknabel** [comment]
Hi @alejandrostateside! Thanks for the report.

You are currently using version 1.2.6. Does this also happen on the latest 1.2.7 from the marketplace?
The error E2BIG is highly specific to the setup and project. Therefore I have lots of questions to further break down your error.

When did this error occur (on start, in specific files, ...)?
Which project did you use?
Did you open a folder containing multiple projects?
How long is the path to your project?
Could you post your vscode config?
Does your project use a SwiftLint config?
How many Swift files do you have within your project (a few, hundreds, thousands)?
How many warnings does `swiftlint lint` emit?

What happens if you follow these steps:

```
$ mkdir ExampleProject
$ cd ExampleProject
$ swift package init
$ code .
```
