### ISSUE TITLE
Report EBADF write EBADF

### ISSUE THREAD

**Issue by freak4pc** [vknabel/vscode-swiftlint#28]
```
Error: write EBADF
	at afterWriteDispatched (internal/stream_base_commons.js:154:25)
	at writeGeneric (internal/stream_base_commons.js:145:3)
	at Socket._writeGeneric (net.js:786:11)
	at Socket._write (net.js:798:8)
	at doWrite (_stream_writable.js:403:12)
	at writeOrBuffer (_stream_writable.js:387:5)
	at Socket.Writable.write (_stream_writable.js:318:11)
	at Socket.Writable.end (_stream_writable.js:585:10)
	at Socket.end (net.js:590:31)
	at /Users/shai.mishali/.vscode-insiders/extensions/vknabel.vscode-swiftlint-1.4.0/out/lint.js:182:24
	at new Promise (<anonymous>)
	at execSwiftlint (/Users/shai.mishali/.vscode-insiders/extensions/vknabel.vscode-swiftlint-1.4.0/out/lint.js:156:12)
	at Object.<anonymous> (/Users/shai.mishali/.vscode-insiders/extensions/vknabel.vscode-swiftlint-1.4.0/out/lint.js:29:38)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/shai.mishali/.vscode-insiders/extensions/vknabel.vscode-swiftlint-1.4.0/out/lint.js:5:58)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
os: darwin
```

**Comment by freak4pc** [comment]
Not too sure what this error is :)

**Comment by vknabel** [comment]
Hi @freak4pc!
Huh, that looks weird, indeed. 🤔

Was this a one-time-error or is it reproducible?
Is there anything special in your setup?
Does it only happen in vscode insiders or also in prod?

**Comment by freak4pc** [comment]
Seems to happen on prod as well. Only special thing I can think of is using a Silicon (M1) MacBook... could be related?

**Comment by vknabel** [comment]
@freak4pc did you still receive warnings / errors from swiftlint?

**Comment by freak4pc** [comment]
I just got the latest VScode build, if this pops again I'll open a new one. Didn't write much Swift in VSCode lately.
Thanks for checking in!
