### ISSUE TITLE
Report EBADF write EBADF

### ISSUE THREAD

**Issue by CyberDex** [vknabel/vscode-swiftlint#31]
```
Error: write EBADF
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Socket.Writable.end (_stream_writable.js:585:10)
    at Socket.end (net.js:590:31)
    at /Users/dex/.vscode/extensions/vknabel.vscode-swiftlint-1.4.0/out/lint.js:182:24
    at new Promise (<anonymous>)
    at execSwiftlint (/Users/dex/.vscode/extensions/vknabel.vscode-swiftlint-1.4.0/out/lint.js:156:12)
    at Object.<anonymous> (/Users/dex/.vscode/extensions/vknabel.vscode-swiftlint-1.4.0/out/lint.js:29:38)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dex/.vscode/extensions/vknabel.vscode-swiftlint-1.4.0/out/lint.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
os: darwin
```

**Comment by vknabel** [comment]
Hey @CyberDex!

Was this a one-time-error or is it reproducible?
Is there anything special in your setup?
Does it only happen in vscode insiders or also in prod?
Do you have a new M1 MacBook (idea from #28)?

**Comment by vknabel** [comment]
In [1.4.2](https://github.com/vknabel/vscode-swiftlint/releases/tag/1.4.2) I added a link to this issue whenever a user experiences this issue.
