### ISSUE TITLE
Report  Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by rcarag** [vknabel/vscode-swiftlint#33]
I keep getting the following error notification when I press CMD+S to save the current file:

<img width="460" alt="image" src="https://user-images.githubusercontent.com/5708469/119028274-d951f180-b9d9-11eb-9392-80e8ca262e05.png">

```
TypeError: Cannot read property '0' of undefined
	at SwiftLint.<anonymous> (/Users/robert/.vscode/extensions/vknabel.vscode-swiftlint-1.4.5/out/SwiftLintProvider.js:53:56)
	at Generator.next (<anonymous>)
	at /Users/robert/.vscode/extensions/vknabel.vscode-swiftlint-1.4.5/out/SwiftLintProvider.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/robert/.vscode/extensions/vknabel.vscode-swiftlint-1.4.5/out/SwiftLintProvider.js:4:12)
	at SwiftLint.lintDocument (/Users/robert/.vscode/extensions/vknabel.vscode-swiftlint-1.4.5/out/SwiftLintProvider.js:47:16)
	at /Users/robert/.vscode/extensions/vknabel.vscode-swiftlint-1.4.5/out/SwiftLintProvider.js:33:22
	at fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at i.$acceptModelSaved (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:145894)
	at l._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:12836)
	at l._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:12520)
	at l._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:11187)
	at l._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:9973)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:8074
	at fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at S.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15497)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:29764
	at fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at S.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15497)
	at t._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:20755)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17641
	at fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12862)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12210
	at Socket.v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:13195)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
os: darwin
```

**Comment by vknabel** [comment]
Hi @rcarag, thanks for the report!
I just released a fix in 1.4.6.
