### ISSUE TITLE
Report ERR_INVALID_ARG_VALUE The argument 'file' cannot be empty. Received ''

### ISSUE THREAD

**Issue by AlexisVidal** [vknabel/vscode-swiftlint#34]
```
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''
	at normalizeSpawnArguments (child_process.js:423:11)
	at spawn (child_process.js:560:13)
	at Object.execFile (child_process.js:246:17)
	at Object.t.<computed> [as execFile] (electron/js2c/asar_bundle.js:5:2242)
	at Object.execShell (c:\Users\alexis.vidal\.vscode\extensions\vknabel.vscode-swiftlint-1.4.5\out\execShell.js:6:37)
	at c:\Users\alexis.vidal\.vscode\extensions\vknabel.vscode-swiftlint-1.4.5\out\lint.js:169:34
	at new Promise (<anonymous>)
	at execSwiftlint (c:\Users\alexis.vidal\.vscode\extensions\vknabel.vscode-swiftlint-1.4.5\out\lint.js:157:12)
	at Object.<anonymous> (c:\Users\alexis.vidal\.vscode\extensions\vknabel.vscode-swiftlint-1.4.5\out\lint.js:61:38)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\alexis.vidal\.vscode\extensions\vknabel.vscode-swiftlint-1.4.5\out\lint.js:5:58)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
os: win32
```

**Comment by vknabel** [comment]
Hey @AlexisVidal, thanks for opening an issue!

It seems you are using windows, right? Do you still remember when this error occurs? Did you use a workspace? What was your file named?

**Comment by vknabel** [comment]
Closed due to inactivity
