### ISSUE TITLE
Report ERR_CHILD_PROCESS_STDIO_MAXBUFFER stdout maxBuffer length exceeded

### ISSUE THREAD

**Issue by petergi** [vknabel/vscode-swiftlint#5]
`RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER] [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at Socket.onChildStdout (child_process.js:363:14)
    at Socket.emit (events.js:200:13)
    at Socket.EventEmitter.emit (domain.js:471:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:271:13)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)`

**Comment by vknabel** [comment]
thank you for your bug report. Do you remember the situation when the error occurred?

**Comment by vknabel** [comment]
This issue has been fixed in [1.0.4](https://github.com/vknabel/vscode-swiftlint/releases/tag/1.0.4).
If your issue still persists, feel free to reopen this issue!
