### ISSUE TITLE
Report  Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by swift-develop** [vknabel/vscode-swiftlint#61]
```
Error: Illegal argument: line must be non-negative
    at S (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:7:1267)
    at new o (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:13329)
    at /Users/tomgrant/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/out/lint.js:197:31
    at Array.map (<anonymous>)
    at /Users/tomgrant/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/out/lint.js:150:37
    at Generator.next (<anonymous>)
    at fulfilled (/Users/tomgrant/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/out/lint.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
os: darwin
```

**Comment by vknabel** [comment]
Hi @swift-develop. Thanks for the report! Do you still remember when this error occurred?
Was there anything special regarding the document?

**Comment by swift-develop** [comment]
I assume it's an issue with one of our .swiftlint.yml(s) But I can't seem to find a negative integer.

**Comment by vknabel** [comment]
I guess I found the issue. Will be fixed in next release. Thanks!
