### ISSUE TITLE
Report  Unexpected end of JSON input

### ISSUE THREAD

**Issue by haekelmeister** [vknabel/vscode-swiftlint#7]
`SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at Object.<anonymous> (/home/xxx/.vscode/extensions/vknabel.vscode-swiftlint-1.0.3/out/lint.js:43:30)
	at Generator.next (<anonymous>)
	at fulfilled (/home/xxx/.vscode/extensions/vknabel.vscode-swiftlint-1.0.3/out/lint.js:5:58)`

**Comment by vknabel** [comment]
Thanks for your report!

This issue has been fixed in [1.0.4](https://github.com/vknabel/vscode-swiftlint/releases/tag/1.0.4).
If your issue still persists, feel free to reopen this issue!
