### ISSUE TITLE
Report  Aliased anchor not found: /.build

### ISSUE THREAD

**Issue by bvanderw** [vknabel/vscode-swiftlint#88]
```
YAMLReferenceError: Aliased anchor not found: /.build
    at resolveNodeValue (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/node_modules/yaml/dist/resolveSeq-d03cb037.js:1568:19)
    at resolveNode (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/node_modules/yaml/dist/resolveSeq-d03cb037.js:1629:15)
    at resolveBlockSeqItems (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/node_modules/yaml/dist/resolveSeq-d03cb037.js:2012:20)
    at Object.resolveSeq [as resolve] (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/node_modules/yaml/dist/resolveSeq-d03cb037.js:1975:79)
    at resolveByTagName (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/node_modules/yaml/dist/resolveSeq-d03cb037.js:1430:25)
    at resolveTag (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/node_modules/yaml/dist/resolveSeq-d03cb037.js:1460:17)
    at resolveNodeValue (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/node_modules/yaml/dist/resolveSeq-d03cb037.js:1581:23)
    at resolveNode (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/node_modules/yaml/dist/resolveSeq-d03cb037.js:1629:15)
    at resolveBlockMapItems (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/node_modules/yaml/dist/resolveSeq-d03cb037.js:1823:38)
    at Object.resolveMap [as resolve] (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/node_modules/yaml/dist/resolveSeq-d03cb037.js:1658:79)
    at resolveByTagName (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/node_modules/yaml/dist/resolveSeq-d03cb037.js:1430:25)
    at resolveTag (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/node_modules/yaml/dist/resolveSeq-d03cb037.js:1460:17)
    at resolveNodeValue (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/node_modules/yaml/dist/resolveSeq-d03cb037.js:1581:23)
    at Object.resolveNode (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/node_modules/yaml/dist/resolveSeq-d03cb037.js:1629:15)
    at parseContents (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/node_modules/yaml/dist/Document-9b4560a1.js:357:30)
    at Document.parse (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/node_modules/yaml/dist/Document-9b4560a1.js:615:5)
    at parseDocument (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/node_modules/yaml/dist/index.js:44:37)
    at Object.parse (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/node_modules/yaml/dist/index.js:55:15)
    at Function.<anonymous> (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/out/SwiftLintConfig.js:38:33)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/bvanderw/.vscode/extensions/vknabel.vscode-swiftlint-1.8.3/out/SwiftLintConfig.js:5:58)
os: darwin
```

**Comment by vknabel** [comment]
Hi, it seems your SwiftLint config was invalid. Make sure it is valid YAML
